### ISSUE TITLE
install script fails at go internal api setup

### ISSUE THREAD

**Issue by JustLokust** [mentholmike/wagmios#1]
```
...
go version go1.18.3 linux/amd64
Installing Go dependencies...
go: added github.com/gorilla/mux v1.8.1
go: added github.com/rs/cors v1.11.1
go: added github.com/joho/godotenv v1.5.1
go: added github.com/lib/pq v1.10.9
go: added github.com/cespare/xxhash/v2 v2.1.2
go: added github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: added github.com/go-redis/redis/v8 v8.11.5
Setting up backend...
Creating go.mod file...
Checking wagmios-backend service status...
● wagmios-backend.service - WAGMIOS Backend Service
     Loaded: loaded (/etc/systemd/system/wagmios-backend.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2025-03-03 10:50:39 CET; 2s ago
    Process: 209815 ExecStart=/usr/local/go/bin/go run /home/server/wagmios/backend-go/cmd/server/main.go (code=exited, status=1/FAILURE)
   Main PID: 209815 (code=exited, status=1/FAILURE)
        CPU: 422ms
```

manual start of go results in the following log:
```

server@server:~/wagmios$ /usr/local/go/bin/go run /home/server/wagmios/backend-go/cmd/server/main.go
backend-go/cmd/server/main.go:8:2: package wagmios/internal/api is not in GOROOT (/usr/local/go/src/wagmios/internal/api)
```

**Comment by mentholmike** [comment]
> ```
> ...
> go version go1.18.3 linux/amd64
> Installing Go dependencies...
> go: added github.com/gorilla/mux v1.8.1
> go: added github.com/rs/cors v1.11.1
> go: added github.com/joho/godotenv v1.5.1
> go: added github.com/lib/pq v1.10.9
> go: added github.com/cespare/xxhash/v2 v2.1.2
> go: added github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
> go: added github.com/go-redis/redis/v8 v8.11.5
> Setting up backend...
> Creating go.mod file...
> Checking wagmios-backend service status...
> ● wagmios-backend.service - WAGMIOS Backend Service
>      Loaded: loaded (/etc/systemd/system/wagmios-backend.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Mon 2025-03-03 10:50:39 CET; 2s ago
>     Process: 209815 ExecStart=/usr/local/go/bin/go run /home/server/wagmios/backend-go/cmd/server/main.go (code=exited, status=1/FAILURE)
>    Main PID: 209815 (code=exited, status=1/FAILURE)
>         CPU: 422ms
> ```
> 
> manual start of go results in the following log:
> 
> ```
> 
> server@server:~/wagmios$ /usr/local/go/bin/go run /home/server/wagmios/backend-go/cmd/server/main.go
> backend-go/cmd/server/main.go:8:2: package wagmios/internal/api is not in GOROOT (/usr/local/go/src/wagmios/internal/api)
> ```

Hey, 

I just released a new version that should take care of this. Can you try to pull  the repo and run sudo docker compose up -d ?

**Comment by JustLokust** [comment]
This fixes a lot of problems, nice.

I had to change the API Port in the docker compose to 8085 since there is already a different service running on 8080.

I changed the upper part of the compose to this:

```
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wagmios-frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8085
    networks:
      - wagmios-network
    restart: unless-stopped
    volumes:
      - frontend_data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wagmios-backend
    ports:
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backend_data:/app/data
    environment:
      - PORT=8085
      - WILLOW_URL=http://willow:5678
    networks:
      - wagmios-network
    restart: unless-stopped
```

The Frontend will still try to fetch its API Data from Port 8080 though.
Seems like the env variable readout is faulty?
