### ISSUE TITLE
Marketplace is not loading

### ISSUE THREAD

**Issue by Node815** [mentholmike/wagmios#2]
Fresh install tonight, I discovered this from https://selfh.st 's site. 

Upon clicking the Marketplace, there is no activity other than the spinner:

![Image](https://github.com/user-attachments/assets/3700862f-9338-400d-9199-2cd3184dcdf3)

Unfortunately, the logs don't indicate what is happening unless there is a debug I can enable for this to help.

Editing this to add another shot, I used a different browser (Vivaldi) and it revealed a bit more hoping this may be of more assistance.

![Image](https://github.com/user-attachments/assets/6d06dbcc-fd88-450c-82e0-9065b481c3d8)

**Comment by mentholmike** [comment]
Hey thanks for reaching out! 

Whats your set up? I want to see if I can simulate it? 

The marketplace refers to a json file in an another repo. I think it may be a cors issue? it seems to be trying to fetch the wrong file. 


can you try right clicking and opening hp inspect. once the dev console pops up go to the network tab and refresh the page. Can you send what it says?

**Comment by Node815** [comment]
It does look a CORS issue, but I had to modify my compose as port 8080 was in use by another app.  (SUPER SUPER COMMON PORT USED by everyone it seems)  : )   This is my compose.  I ran the git pull as specified from your REAEDME.MD:

```
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wagmios-frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4080
    networks:
      - wagmios-network
    restart: unless-stopped
    volumes:
      - frontend_data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wagmios-backend
    ports:
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backend_data:/app/data
    environment:
      - PORT=4080
      - WILLOW_URL=http://willow:5678
    networks:
      - wagmios-network
    restart: unless-stopped

  willow:
    image: n8nio/n8n
    container_name: willow
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_DEFAULT_WORKFLOW_STATE=active
      - N8N_LOG_LEVEL=info
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=willow_memories
      - DB_POSTGRESDB_USER=willow
      - DB_POSTGRESDB_PASSWORD=wagmios
    volumes:
      - willow_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - wagmios-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=willow
      - POSTGRES_PASSWORD=wagmios
      - POSTGRES_DB=willow_memories
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wagmios-network

networks:
  wagmios-network:
    driver: bridge

volumes:
  willow_data:
  postgres_data:
  frontend_data:
  backend_data: 
```

Taken from Waterfox: 

![Image](https://github.com/user-attachments/assets/9e5a0d49-7848-463b-901f-4ac720b82a67) 

```OPTIONS /api/system/metrics undefined
Host: 192.168.1.161:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type
Referer: http://192.168.1.161:5174/
Origin: http://192.168.1.161:5174
Sec-GPC: 1
Connection: keep-alive
Priority: u=4```

As a side note, I have well over 30 containers on my network and was intrigued by the AI  management.   It would be pretty cool if you could have it parse the existing containers on the server for management.  I know this is in the early development stages, but it might be worth considering.
